@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.acessToken}}

# @name create_user
POST {{baseUrl}}/usuarios
Content-Type: application/json

{
  "name": "Fulano Teste",
  "email": "Futeste@mail.com",
  "password": "12345678"
}

###

# @name authenticate
POST {{baseUrl}}/sessao
Content-Type: application/json

{
  "email": "Futeste@mail.com",
  "password": "12345678"
}

###

# @name create_task
POST {{baseUrl}}/tarefas
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "tarefaa teste 01",
  "status": "pendente",
  "description": "desscrição da tarefa",
  "tag": "testse 01"
}

###

# @name list_tasks
GET {{baseUrl}}/tarefas
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name delete_task
DELETE  {{baseUrl}}/tarefas/{id da task}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name update_task
PUT {{baseUrl}}/tarefas/{id da task}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "tarefaa teste 01",
  "status": "concluida",
  "description": "desscrição da tarefa",
  "tag": "testse 01"
}

###

# @name update_profile
PATCH {{baseUrl}}/usuarios/perfil
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "fulano troca de nome",
  "oldPassword": "12345678",
  "newPassword": "123456789"
}


